- name: Setup hetzner resources
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - hetzner

- name: Apply server configuration
  hosts: servers
  remote_user: root
  vars:
    docker_compose_version: "2.20.2"
    mailcow__install_path: "/opt/mailcow-dockerized"
    mailcow__hostname: "{{ hostname }}"
    mailcow__git_version: "{{ mailcow_version }}"
    mailcow__timezone: "{{ timezone }}"
    mailcow__redirect_http_to_https: yes
    mailcow__config_use_watchdog: yes
    mailcow__config_additional_server_names: "{{ ['mta-sts.*'] if mta_sts else [] }}"
    mailcow__config_additional_san: "{{ ['mta-sts.*'] if mta_sts else [] }}"
    mailcow__config_watchdog_notify_email: "{{ mailcow_watchdog_contact }}"
    mailcow__config_acme_contact: "{{ mailcow_acme_contact }}"
  environment:
    BORG_RSH: ssh -o StrictHostKeyChecking=no
  roles:
    - server
    - mailcow
    - mailcow-customized
